name: heart-disease-predictor
channels:
  - conda-forge
  - pytorch
  - anaconda
  - plotly
  - defaults
dependencies:
  - python==3.10
  - conda=25.7.0
  - mamba=2.1.1
  - pip
  - jupytext
  - jupyterlab
  - conda-lock
  - matplotlib
  - pandas
  - nb_conda_kernels
  - scikit-learn
  - requests
  - ipython
  - graphviz
  - python-graphviz
  - jinja2
  - lightgbm
  - torchvision
  - torchaudio
  - pytorch
  - autograd
  - plotly
  - panel
  - watchfiles
  - altair-all
  - vega_datasets